config/routes.rb
# encoding: utf-8
Rails.application.routes.draw do

  root to: 'public#index'

  post 'create_invoice', to: 'webhooks#create_invoice'
  post 'changed_invoice', to: 'webhooks#changed_invoice'
  post 'changed_subscription', to: 'webhooks#changed_subscription'
  post 'subscription_changed', to: 'webhooks#subscription_changed'
  post 'activate_subscription', to: 'webhooks#activate_subscription'
  post 'expired_subscription', to: 'webhooks#expired_subscription'
  post 'suspended_subscription', to: 'webhooks#suspended_subscription'
  post 'subscription_renewed', to: 'webhooks#subscription_renewed'
  get 'password-reset', to: 'application#password_reset', as: 'password_reset'


  devise_for :users
  devise_for :admins, path: 'admin', path_names: {sign_in: 'login',   sign_out: 'logout', password: 'senha'}
  devise_for :companies, path: 'empresa', path_names: {sign_in: 'login',   sign_out: 'logout', password: 'senha'}

  get '/api', to: 'api#index'
  namespace :api do
    namespace :v1 do
      resources :users, only: [:create] do
        collection do
          get  'me'
          post 'auth'
          post 'device'
          post 'facebook_auth'
          put  'update'
          put  'update_image', path: 'update-image'
          post 'change_payment_method'
          delete 'logout'
          put  'password', path: 'update-password'
          post 'recover',  path: 'recover'
        end
      end

      scope 'user' do
        resources :vehicles,  except: [:new, :edit]
        resources :subscriptions
        resources :schedules, only: [:update, :show, :index, :destroy]
        resources :addresses, except: [:new, :edit] do
          collection do
              post 'zipcode'
          end
        end
      end

      resources :plans, only: [:index, :show] do
        get 'avaiables', on: :collection
      end

      resources :brands, only: [:index, :show]

      resources :companies, only: [:show] do
        resources :company_ratings, path: 'ratings', only: [:index, :create]
        resources :schedules, only: [:new, :create]
        collection do
          get 'near'
          get 'services'
          get 'search'
        end

        member do
          get 'calendar'
        end
      end
    end
  end

  #company
  get 'empresa', to: 'company#index', as: 'company'
  namespace :company , path: 'empresa' do
    resources :schedules, path: 'agendamentos', path_names: {new: 'novo', create: 'criar', update: 'atualizar'} do
      collection do
        get 'do-dia', as: 'todays', action: 'todays'
        get 'search_by_status', as: 'status', action: 'search_by_status'
        get 'search_by_date', as: 'date', action: 'search_by_date'
      end
      post 'finalizado', as: 'finished', action: 'finished', on: :member
      post 'abandonado', as: 'abandoned', action: 'abandoned', on: :member
    end

    resources :companies, path: 'dados-da-empresa', only: [:edit, :update]
  end

  #admin
  get 'admin', to: 'admin#index', as: 'admin'
  namespace :admin do

    resources :availabilities, path: 'disponibilidades', path_names: {new: 'novo', create: 'criar', update: 'atualizar'} do
      collection do
        get 'buscar', as: 'search', action: 'search'
      end
    end

    resources :brands, path: 'marcas', path_names: {new: 'novo', create: 'criar', update: 'atualizar'} do
      collection do
        get 'buscar', as: 'search', action: 'search'
      end
    end

    resources :companies, path: 'empresas', path_names: {new: 'novo', create: 'criar', update: 'atualizar'} do
      collection do
        get 'buscar', as: 'search', action: 'search'
      end
    end

    resources :holidays, path: 'feriados', path_names: {new: 'novo', create: 'criar', update: 'atualizar'} do
      collection do
        get 'buscar-por-data', as: 'search_by_date', action: 'search_by_date'
        get 'buscar-por-cidade', as: 'search_by_city', action: 'search_by_city'
        get 'buscar-por-estado', as: 'search_by_state', action: 'search_by_state'
        get 'cities_by_state/:id', action: 'cities_by_state'
      end
    end

    resources :invoices, path: 'pagamentos', path_names: {new: 'novo', create: 'criar', update: 'atualizar'} do
      collection do
        get 'buscar-por-data', as: 'search_by_date', action: 'search_by_date'
      end
    end

    resources :plans, path: 'planos', path_names: {new: 'novo', create: 'criar', update: 'atualizar'} do
      collection do
        get 'buscar', as: 'search', action: 'search'
      end
    end

    resources :services, path: 'servicos', path_names: {new: 'novo', create: 'criar', update: 'atualizar'} do
      collection do
        get 'buscar', as: 'search', action: 'search'
      end
    end

    resources :subscriptions, path: 'subscrição', path_names: {new: 'novo', create: 'criar', update: 'atualizar'} do
      collection do
        get 'buscar-por-empresa', as: 'search_by_company', action: 'search_by_company'
        get 'buscar-por-usuario', as: 'search_by_user', action: 'search_by_user'
        get 'buscar-por-plano', as: 'search_by_plan', action: 'search_by_plan'
      end
    end

    resources :users, path: 'usuarios', path_names: {new: 'novo', create: 'criar', update: 'atualizar'} do
      collection do
        get 'buscar', as: 'search', action: 'search'
      end
    end

    resources :user_schedules, path: 'agendamentos', path_names: {new: 'novo', create: 'criar', update: 'atualizar'} do
      collection do
        get 'buscar', as: 'search', action: 'search'
        get 'buscar-por-empresa', as: 'search_by_company', action: 'search_by_company'
        get 'buscar-por-usuario', as: 'search_by_user', action: 'search_by_user'
        get 'buscar-por-data', as: 'search_by_date', action: 'search_by_date'
      end
    end

  end



end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < AdminController

  before_action :company, only: [:show, :edit, :update]
  before_action :week_days, only: [:edit, :new]

  def index
    @companies = Company.all.order(created_at: :desc).page(params[:page]).per(10)
    @partial = @companies.present? ? 'companies' : 'none'
  end

  def show

  end

  def new
    @company = Company.new
    @company.build_address
    @company.generate_availabilities
  end

  def edit

  end

  def week_days
    @week_days = Availability.active
    @seg = @week_days.seg
    @ter = @week_days.ter
    @qua = @week_days.qua
    @qui = @week_days.qui
    @sex = @week_days.sex
    @sab = @week_days.sab
    @dom = @week_days.dom
  end

  def create
    @company = Company.new(company_params)
    # raise @company.address.inspect
    if @company.save
      flash[:notice] = I18n.t('admin.messages.created_f', model: Company.model_name.human)
      redirect_to [:admin, :companies]
    else
      flash[:notice] =  I18n.t('admin.messages.not_created_f', model: Company.model_name.human)
      @company.build_address
      render 'new'
    end
  end

  def update
    if @company.update_attributes(company_params)
      flash[:notice] = I18n.t('admin.messages.updated_f', model: Company.model_name.human)
      redirect_to [:admin, :companies]
    else
      flash[:notice] = I18n.t('admin.messages.not_updated_f', model: Company.model_name.human)
      render 'edit'
    end
  end

  def search
    criteria = "%#{params[:search][:term]}%"
    result = Company.where('name iLike ?', criteria)
    @count = result.length
    @partial = result.present? ? 'search_result' : 'not_found'
    @companies = result.page(params[:page]).per(12)
    render 'search', format: :js
  end

  def company
    @company = Company.friendly.find(params[:id])
  end

  private

  def company_params
    params.require(:company).permit(:limit_per_hour, :password, :image, :name, :email, :identifier, :registration, :description, :phone, :mobile, :city_id, :active, address_attributes: [:id, :zipcode, :company_id, :street, :number, :neighborhood, :complement, :city, :state], availabilities_attributes: [:id, :week_day, :init, :ends, :_destroy], service_ids: [])
  end

  def address_params
    params.require(:company).permit(address_attributes: [:id, :company_id, :street, :number, :neighborhood, :complement, :city, :state, :zipcode])
  end

end

app/controllers/api/v1/companies_controller.rb
class Api::V1::CompaniesController < ApiController

  before_action :authenticate, except: [:near, :search]

  def search
    criteria = "%#{params[:term]}%"
    @companies_by_name = Company.where('name iLike ?', criteria)
    @companies_by_address = Company.all.joins(:address).where('addresses.city iLike ? or addresses.state iLike ? or addresses.street iLike ? or addresses.neighborhood iLike ?', criteria, criteria, criteria, criteria)
    @companies = @companies_by_address + @companies_by_name
    if @companies.present?
      render_json( @companies.map(&:to_json) )
    else
      render_not_found
    end
  end

  def near
    @companies = Company.near(params[:marker], params[:radius])
    @companies = @companies.collect(&:to_json) if @companies.any?
    render_json(@companies)
  end

  def show
    @company = Company.find_by_id(id)
    @company ? render_json(@company.to_json) : render_not_found
  end

  def services
    @company = Company.find_by_id(id);
    if @company
      @services = @company.services
      @services.any? ? render_json(@services.collect(&:to_json)) : render_json([])
    else
      render_not_found
    end
  end

  def calendar
    @company = Company.find_by_id(id);
    @date    = params[:date].present? ? Date.parse(params[:date]) : Date.today
    if @company
      render_json(@company.calendar(@date))
    else
      render_not_found
    end
  end

  private

  def id
    params.require(:id)
  end

  def schedule_params
    params.require(:schedule).permit(:company_id, :date ,services: [])
  end

end

app/controllers/api/v1/schedules_controller.rb
class Api::V1::SchedulesController < ApiController

  before_action :authenticate

  def index
    schedules = @user.schedules.order(date: :desc)
    if schedules
      render_json( schedules.map(&:to_json) )
    else
      render_not_found
    end
  end

  def new
    company = Company.find(params[:company_id])
    services = @user.prepare_schedule
    calendar = company.calendar
    services.merge!({ calendar: calendar.present? ? calendar : {} })
    render_json( services )
  end

  def create
    token = token_param
    schedule = @user.schedules.build(schedule_params)
    response = schedule.generate_schedule(token)
    if response.is_a?(UserSchedule) && !response.errors.present?
      render_json( schedule.to_json )
    elsif response.is_a?(UserSchedule) && response.errors.present?
      render_unprocessable(schedule)
    else
      render_unprocessable_without_object('Não foi possível efetuar a cobrança dos serviços extras')
    end
  end

  def show
    schedule = @user.schedules.find(params[:id])
    if schedule.present?
      render_json(schedule.to_json)
    else
      render_not_found
    end
  end

  def destroy
    schedule = @user.schedules.find(params[:id])
    if schedule.destroy
      render_json(schedule.to_json)
    else
      render_json(schedule)
    end
  end


  private

  def schedule_params
    params.require(:schedule).permit(:date, :company_id, services:[], extras:[])
  end

  def token_param
    params.require(:token)
  end

end

app/controllers/company/companies_controller.rb
class Company::CompaniesController < CompanyController

  before_action :week_days, only: [:edit, :new]

  def edit
    @company = current_company
  end

  def update
    @company = current_company
    if @company.update_attributes(company_params)
      flash[:notice] = I18n.t('admin.messages.updated_f', model: Company.model_name.human)
      redirect_to [:company]
    else
      flash[:notice] = I18n.t('admin.messages.not_updated_f', model: Company.model_name.human)
      render 'edit'
    end
  end

  def week_days
    @week_days = Availability.active
    @seg = @week_days.seg
    @ter = @week_days.ter
    @qua = @week_days.qua
    @qui = @week_days.qui
    @sex = @week_days.sex
    @sab = @week_days.sab
    @dom = @week_days.dom
  end

  private

  def company_params
    params.require(:company).permit(:limit_per_hour, :name, :email, :identifier, :registration, :description, :phone, :mobile, :city_id, :active, address_attributes: [:id, :company_id, :street, :number, :neighborhood, :complement, :city, :state],availabilities_attributes: [:id, :week_day, :init, :ends, :_destroy], service_ids: [])
  end

  def search_params
    params.require(:search).permit(:date, :status)
  end

end

app/controllers/company/schedules_controller.rb
class Company::SchedulesController < CompanyController

  def todays
    @company = current_company
    @schedules = @company.schedules.pending.todays.order(date: :desc).page(params[:page]).per(12)
    @partial = @schedules.present? ? 'todays' : 'none'
  end

  def index
    @company = current_company
    @schedules = @company.schedules.order(date: :desc).page(params[:page]).per(12)
    @partial = @schedules.present? ? 'schedules' : 'none'
  end

  def finished
    @schedule = UserSchedule.friendly.find(params[:id])
    @schedule.finished
    flash[:notice] = "Agendamento finalizado!"
    @user = @schedule.user
    redirect_to [:todays, :company, :schedules]
  end

  def abandoned
    @schedule = UserSchedule.friendly.find(params[:id])
    @schedule.abandoned
    flash[:notice] = "Agendamento finalizado!"
    @user = @schedule.user
    redirect_to [:todays, :company, :schedules]
  end

  def search_by_status
    status = search_params[:status]
    @company = current_company
    if status.eql?("Pendente")
      @schedules = @company.schedules.pending.page(params[:page]).per(12)
    else
      @schedules = @company.schedules.finished.page(params[:page]).per(12)
    end
    @partial = @schedules.present? ? 'search_result' : 'not_found'
    render 'search'
  end

  def search_by_date
    date_init = DateTime.parse(search_params[:date])
    date_end = DateTime.parse(search_params[:date]).end_of_day
    @company = current_company
    @schedules = @company.schedules.where('date >= ? AND date <= ?', date_init, date_end)
    @partial = @schedules.present? ? 'search_result' : 'not_found'
    render 'search'
  end


  private

  def search_params
    params.require(:search).permit(:date, :status)
  end

end

app/controllers/company_controller.rb
class CompanyController < ApplicationController
  before_action :authenticate_company!

  def index

  end

end

app/views/company/schedules/_none.html.slim
.section.no-result
  .icon
    i.dripicons-calendar

  h3 Desculpe, não existem agendamentos para exibição.

app/views/company/schedules/_schedules.html.slim
.section
  #accordion.accordion-companies role="tablist"

    - @schedules.each_with_index do |schedule, index|
      .card
        .card-header role="tab" id="heading#{index}"
          .row
            .col.col-sm-4
              = link_to "#collapse#{index}", data: {toggle: 'collapse'}, aria: {expanded: 'true', controls: "collapse#{index}"} do
                i.icon.dripicons-calendar
                h5.mb-0= schedule.user
                p: small <i class="dripicons-calendar"></i> #{l(schedule.date, format: :short)}
            .col.col-sm-4.text-center
              - if schedule.cancelled_at
                span.label.label-danger Cancelado
              - else
                - if schedule.finished_at?
                  span.label.label-success Finalizado
                - else
                  span.label.label-info Pendente
            .col.col-sm-4

        .collapse id="collapse#{index}" role="tabpanel" aria-labelledby="heading#{index}" data-parent="#accordion"
          .card-body
            .row
              .col-12.col-sm-4
                p <strong>Cliente: </strong>#{schedule.user}
              .col-12.col-sm-4
                p <strong>Data de agendamento: </strong>#{l(schedule.date, format: :custom)}
              .col-12.col-sm-4
                p <strong>Empresa: </strong>#{schedule.company}
            .row
              .col-12.col-sm-4
                p <strong>Telefone: </strong>#{schedule.user.phone.present? ? schedule.user.phone : "Não informado"}
              .col-12.col-sm-4
                p <strong>Celular: </strong>#{schedule.user.mobile.present? ? schedule.user.mobile : "Não informado"}
              .col-12.col-sm-4
                p <strong>E-mail: </strong>#{schedule.user.email}

app/views/company/schedules/_search_result.html.slim
- if params[:action] == "search" || params[:action] == "filter"
  h3.title(style="margin-top: 0;")
  .row
    .col-xs-12.col-sm-6.col-md-6
      h2 Resultados da busca
    .col-xs-12.col-sm-12.col-md-12
      = link_to 'Limpar busca', [:company, :schedules], title: "Limpar busca", class: 'btn btn-default'

= render 'schedules'

app/views/company/schedules/_todays.html.slim
.section
  #accordion.accordion-companies role="tablist"

    - @schedules.each_with_index do |schedule, index|

      .card
        .card-header role="tab" id="heading#{index}"
          .row
            .col.col-sm-4
              = link_to "#collapse#{index}", data: {toggle: 'collapse'}, aria: {expanded: 'true', controls: "collapse#{index}"} do
                i.icon.dripicons-calendar
                h5.mb-0= schedule.user
                p: small <i class="dripicons-calendar"></i> #{l(schedule.date, format: :short)}
            .col.col-sm-4.text-center
              - if schedule.cancelled_at
                span.label.label-danger Cancelado
              - else
                - if schedule.finished_at?
                  span.label.label-success Finalizado
                - else
                  span.label.label-info Pendente
            .col.col-sm-4
              .btn-group.btn-group-sm.float-right.btn-actions role="group" aria-label="Actions group"
                = link_to "Finalizado", finished_company_schedule_path(schedule), method: 'post', class: "btn btn-secondary"
                = link_to "Não Compareceu", abandoned_company_schedule_path(schedule), method: 'post', class: "btn btn-danger"

        .collapse id="collapse#{index}" role="tabpanel" aria-labelledby="heading#{index}" data-parent="#accordion"
          .card-body
            .row
              .col-12.col-sm-4
                p <strong>Cliente: </strong>#{schedule.user}
              .col-12.col-sm-4
                p <strong>Data de agendamento: </strong>#{l(schedule.date, format: :custom)}
              .col-12.col-sm-4
                p <strong>Empresa: </strong>#{schedule.company}
            .row
              .col-12.col-sm-4
                p <strong>Telefone: </strong>#{schedule.user.phone.present? ? schedule.user.phone : "Não informado"}
              .col-12.col-sm-4
                p <strong>Celular: </strong>#{schedule.user.mobile.present? ? schedule.user.mobile : "Não informado"}
              .col-12.col-sm-4
                p <strong>E-mail: </strong>#{schedule.user.email}

app/views/company/schedules/index.html.slim
- content_for :head do
  title AppWash - Agendamentos

.section.mt-30.mb-30
  .container
    .row
      .col-12.col-sm-4
        .title-section.section
          h1 Agendamentos
          ol.breadcrumb
            li.breadcrumb-item= link_to '<i class="dripicons-home"></i>'.html_safe, [:company], title: 'Dashboard'
            li.breadcrumb-item.active Agendamentos

          .aside.section
            = simple_form_for :search, url: [:status, :company, :schedules], html: {class: "form-search"}, method: :get, remote: true do |f|
              .form-group
                = f.input :status, collection: ["Pendente", "Finalizado"], prompt: false, input_html: { class: "form-control" }, label: false
              = f.submit "Pesquisar", class: "btn btn-secondary"

          .aside.section
            = simple_form_for :search, url: [:date, :company, :schedules], html: {class: "form-search"}, method: :get, remote: true do |f|
              .form-group
                = f.input :date, as:'string', prompt: false, input_html: { class: "form-control date" }, label: false
              = f.submit "Pesquisar", class: "btn btn-secondary"
      .col-12.col-sm-8

        .result-set
          .section
            = render "#{@partial}"
          .section
            = paginate @schedules

app/views/company/schedules/search.js.erb
$('.result-set').html("<%= j render(partial: @partial) %>")

app/views/company/schedules/todays.html.slim
- content_for :head do
  title AppWash - Agendamentos do Dia

.section.mt-30.mb-30
  .container
    .row
      .col-12.col-sm-4
        .title-section.section
          h1 Agendamentos do Dia
          ol.breadcrumb
            li.breadcrumb-item= link_to '<i class="dripicons-home"></i>'.html_safe, [:company], title: 'Dashboard'
            li.breadcrumb-item.active Agendamentos do Dia

      .col-12.col-sm-8
        .result-set
          .section
            = render "#{@partial}"
          .section
            = paginate @schedules